name: "release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Filtered Release Notes"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marcantondahmen/release-notes-action@0.1.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          filter: "^(feat|fix)"
          strict: true